Adicionando informações do currículo
reprograma/On9-Accenture-S16-Carreira pull request #16
Opened 2020-11-29 04:14 UTC by mariana-franca

2020-12-01 20:37 UTC, borgesdn requested changes

2020-12-01 20:37 UTC, borgesdn commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +      "resumo_conhecimentos_aprendidos": "Criação, realização, divulgação,planejamento de peças publicitárias e elaboração de estratégias de comunicação. "
Falta um espaço antes de "planejamento"

2020-12-01 20:37 UTC, borgesdn commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +      "atividades_desenvolvidas": "Pesquisa(primária e secundária),validação das análises e hipóteses junto aos especialistas de mercado fornecendo insights estratégicos para as unidades de negócios
Espaço depois de "Pesquisa" e antes de "validação"

2020-12-01 20:37 UTC, borgesdn commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +      "atividades_desenvolvidas": "Planejamento e criação de conteúdo para redes sociais, moderadora de comunidade, tradutora e gamer tester. .",
Tem dois pontos no fim da frase

2020-12-01 20:37 UTC, borgesdn commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +    "Realizando assim, uma vontade que surgiu quando eu tinha 25 anos e trabalhei por 3 anos em uma empresa de desenvolvimento de produtos digitais."
Revisar essa frase

2020-12-02 03:24 UTC, mariana-franca commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +    "Realizando assim, uma vontade que surgiu quando eu tinha 25 anos e trabalhei por 3 anos em uma empresa de desenvolvimento de produtos digitais."
Debora, é alguma frase específica ou o texto todo?

2020-12-02 03:32 UTC, mariana-franca commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +    "Realizando assim, uma vontade que surgiu quando eu tinha 25 anos e trabalhei por 3 anos em uma empresa de desenvolvimento de produtos digitais."
Pensei em algo assim: 
"Me chamo Mariana França, tenho 36 anos, nasci na capital do país mas foi em Salvador que me criei e me transformei em mulher.",
"Me formei em comunicação, comecei um mestrado, fui Cofundadora de um Coworking e um Gastrobar. Nesse tempo de vida, já vivi em Brasília, Buenos Aires e agora em Recife.",
"No momento estou me dedicando a estudar programação e por isso estou fazendo um curso técnico de Análise e Desenvolvimento de Sistemas."

2020-12-02 20:52 UTC, borgesdn commented on cvs_base/students_json/Mariana_Martiniano_de_Franca.json
> +    "Realizando assim, uma vontade que surgiu quando eu tinha 25 anos e trabalhei por 3 anos em uma empresa de desenvolvimento de produtos digitais."
Era mais no geral mesmo. Acho que ficou melhor.
Atenção apenas a pontuação:
"nasci na capital do país, mas foi em Salvador"
"No momento, estou me dedicando a estudar"

2020-12-02 22:39 UTC, borgesdn approved these changes

2020-12-02 22:39 UTC, merged