Informações Atualizadas - Denise Duarte
reprograma/On9-Accenture-S16-Carreira pull request #17
Opened 2020-11-29 17:26 UTC by deniseevelin

2020-12-01 20:33 UTC, borgesdn requested changes

2020-12-01 20:33 UTC, borgesdn commented on cvs_base/students/denise_silva.json
> +        "resumo_conhecimentos_aprendidos": "Instanciação, Atributos, Referências, Métodos, Composiçaõ de Objetos, Atributos Privados, Encapsulamrntos e Getters e Setters."
Corrigir palavra "composição"

2020-12-02 02:15 UTC, deniseevelin commented on cvs_base/students/denise_silva.json
> +        "resumo_conhecimentos_aprendidos": "Instanciação, Atributos, Referências, Métodos, Composiçaõ de Objetos, Atributos Privados, Encapsulamrntos e Getters e Setters."
Corrigido. Obrigada!!!!

2020-12-02 20:49 UTC, borgesdn approved these changes

2020-12-02 20:49 UTC, merged