Adicionando a atividade da semana 16
reprograma/On9-Accenture-S16-Carreira pull request #19
Opened 2020-11-29 18:31 UTC by luanaCristina

2020-12-01 20:25 UTC, borgesdn requested changes

2020-12-01 20:25 UTC, borgesdn commented on cvs_base/students_json/luana_silva.json
> +      "resumo_conhecimentos_aprendidos": "Aulas das 9h às 15h com estadia em homestay nativa."
A descrição desse é realmente igual ao anterior?

2020-12-02 01:15 UTC, luanaCristina commented
É não. eu copiei a estrutura e esqueci de mudar o resto. Vou ajustar.
Obrigada.


Luana Cristina de A Silva
Sr Quality Assurance Software (Senior Tester) and BI
Bacharela em Sistemas de Informação (Centro Universitário Maurício de Nassau)
Pós graduada em Engenharia de Software (Unibratec)

Aluna no MBA em Análise de Inteligência de Negócio (IGTI)
Skype e e-mail: luanacrystinne@msn.com<mailto:luanacrystinne@msn.com>

LinkedIn: linkedin.com/in/luanacristinaas

Mobile: (81)9 9900-1226 / 9 8535-1025

________________________________
De: borgesdn <notifications@github.com>
Enviado: terça-feira, 1 de dezembro de 2020 17:26
Para: reprograma/On9-Accenture-S16-Carreira <On9-Accenture-S16-Carreira@noreply.github.com>
Cc: Luana Cristina de A Silva <luanacrystinne@msn.com>; Author <author@noreply.github.com>
Assunto: Re: [reprograma/On9-Accenture-S16-Carreira] Adicionando a atividade da semana 16 (#19)


@borgesdn requested changes on this pull request.

________________________________

In cvs_base/students_json/luana_silva.json<https://github.com/reprograma/On9-Accenture-S16-Carreira/pull/19#discussion_r533699147>:

> +      "curso": "Pós em Engeharia de Software",

+      "instituicao": "UNIBRATEC",

+      "periodo": "Mai/2015 a Mai/2017",

+      "resumo_conhecimentos_aprendidos": "Desenvolvimento de software desde a concepção até a entrega do produto."

+    },

+    {

+      "curso": "Intercâmbio em Inglês na Nova Zelândia",

+      "instituicao": "Academy English Auckland",

+      "periodo": "Out/2014 a Dez/2014",

+      "resumo_conhecimentos_aprendidos": "Aulas das 9h às 15h com estadia em homestay nativa."

+    },

+    {

+      "curso": "Bacharelado em Sistemas de Informação",

+      "instituicao": "Centro Universitário Maurício de Nassau",

+      "periodo": "Out/2014 a Dez/2014",

+      "resumo_conhecimentos_aprendidos": "Aulas das 9h às 15h com estadia em homestay nativa."



A descrição desse é realmente igual ao anterior?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/reprograma/On9-Accenture-S16-Carreira/pull/19#pullrequestreview-542267644>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEGXQE6LAJ2P6NCF4MTKBDTSSVGN3ANCNFSM4UGVYHSQ>.

2020-12-02 20:48 UTC, borgesdn approved these changes

2020-12-02 20:48 UTC, merged