Entrega currículo semana S16 - Aline Santos
reprograma/On9-Accenture-S16-Carreira pull request #24
Opened 2020-11-29 23:30 UTC by aline-pereira

Entrega currículo semana S16 - Aline Santos

2020-12-01 20:17 UTC, borgesdn requested changes
Corrigir a grafia da palavra duração

2020-12-01 20:17 UTC, borgesdn commented on cvs_base/students/aline_pereira_santos.json
> +            "resumo_conhecimentos_aprendidos": "Curso com duraçõa de 1 ano e 6 meses que abordou análise de sistemas, gestão de sistemas, técnica orientada a objetos, linguagens para banco de dados,
Corrigir duração

2020-12-01 22:13 UTC, aline-pereira commented
corrigido

2020-12-02 20:47 UTC, borgesdn approved these changes

2020-12-02 20:47 UTC, merged