Entrega da semana - Carreira
reprograma/On9-Accenture-S16-Carreira pull request #4
Opened 2020-11-28 00:00 UTC by ElianeASilva

2020-12-01 21:15 UTC, borgesdn requested changes
Verificar estrutura de pastas especificadas

2020-12-02 02:46 UTC, ElianeASilva commented
> Verificar estrutura de pastas especificadas

Feito, Debora.

2020-12-02 02:47 UTC, ElianeASilva commented
Estrutura de pastas corrigidas.

2020-12-02 20:54 UTC, borgesdn approved these changes

2020-12-02 20:54 UTC, merged